name: Yearly CI

on:
  pull_request:
    paths:
      - '**'
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Deps
        run: npm --loglevel verbose ci

      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install npm@latest
        run: npm install -g npm@latest

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Deps
        run: npm ci

      - name: Pre-build
        run: npm run prebuild